[plugins]
plugins-dir = '/usr/lib/modality-reflector-plugins'

[ingest]
additional-timeline-attributes = [
    "ci_job='${GITHUB_JOB-local}'",
    "ci_commit='${GITHUB_SHA-local}'",
    "ci_git_commit='${GIT_COMMIT-local}'",
]
override-timeline-attributes = [
    "run_id='${MODALITY_RUN_ID-1}'",
]

[plugins.ingest.importers.defmt]
additional-timeline-attributes = [
    "platform='RTICv1'",
    "module='test-system'",
]

[plugins.ingest.importers.defmt.metadata]
client-timeout = "2s"
open-timeout = "10s"
rtos-mode = "rtic1"
# NOTE: this is inside the docker container's fs
elf-file = "/atsamd-rtic-firmware"
file = "/rtt_log.bin"
